name: Docker Image CI

on:
  push:
    branches: [ "stage" ]

env:
  REGISTRY: jcalderon
  IMAGE_NAME: public
  OPS_BRANCH: main
  OPS_REPO: cachac/ops

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # checkout github code
        name: Checkout code
        with:
          fetch-depth: 0 # fetch tags
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          push: true
        # file: ./path-to-dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest  
          build-args: |
            APP_ENV=${{ secrets.APP_ENV }
      - name: Build the Docker image
        run: docker run --rm --name api -p 3000:3000 cachac/IMAGE_NAME