name: Docker Image CI

on:
  push:
    branch: [ "stage" ]

env:
  REGISTRY: jcalderon
  IMAGE_NAME: public
  OPS_BRANCH: main
  OPS_REPO: jahazielcr/ops

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
        with:
          fetch-depth: 0

       - name: login to Dockerhub
         uses: docker/login-action@v2
         with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Build & Push
         uses: docker/build-push-actions@v3
         with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            APP_ENV= ${{ secret.APP_ENV  }}

       - name: Run test
         run: docker run --rm --name api -p 3000:3000 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest 