name: Docker Image CI

on:
  push:
    branch: ["stage"]

env:
  REGISTRY: jcalderon
  IMAGE_NAME: public:1.0.0
  OPS_BRANCH: main
  OPS_REPO: jahazielcr/ops

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
        with:
          fetch-depth: 0

       - name: logint to Dockerhub
         uses: docker/login-action@v2
         with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

