name: hello-world
# trigger
on:
  push:
    branch: ["stage"]
# pipeline
jobs:
  print: # job name
	  # ejecuta el pipeline en una VM Ubuntu
    runs-on: ubuntu-latest # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

    # Pasos a ejecutar
    steps:
      - name: print-to-screen
        run: echo "Hello World!"