name: hello-world

on:
  push:
    branch: ["stage"]

env:
  TEXT: "Jahaziel Josias Calderon Cabezas"

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: print-to-screen
        run: echo "Hello World ${{ env.TEXT }}!"